import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { SEOHead } from "@/components/SEOHead";
import { DEPARTMENTS_CATALOG } from "@/data/agents-catalog";
import {
  ArrowRight, Bot, Search, FileText, BarChart3, Shield,
  Zap, TrendingUp, Users, CheckCircle, Globe, Lock,
  Bell, Workflow, Clock, Layers
} from "lucide-react";

const CORE_FEATURES = [
  {
    icon: Bot,
    titleFr: "39 Agents IA Spécialisés",
    titleEn: "39 Specialized AI Agents",
    descFr: "Chaque agent a un rôle précis, des compétences uniques et travaille 24/7 pour votre entreprise.",
    descEn: "Each agent has a precise role, unique skills, and works 24/7 for your business.",
    color: "#6366f1",
  },
  {
    icon: Layers,
    titleFr: "11 Départements Métier",
    titleEn: "11 Business Departments",
    descFr: "Marketing, Commercial, Finance, Sécurité, Produit, Ingénierie, Data, Support, Gouvernance, RH, Juridique.",
    descEn: "Marketing, Sales, Finance, Security, Product, Engineering, Data, Support, Governance, HR, Legal.",
    color: "#8b5cf6",
  },
  {
    icon: Shield,
    titleFr: "Approbation Humaine",
    titleEn: "Human Approval",
    descFr: "Les actions à risque nécessitent votre validation. Vous gardez le contrôle, l'IA exécute.",
    descEn: "Risky actions require your validation. You keep control, AI executes.",
    color: "#10b981",
  },
  {
    icon: BarChart3,
    titleFr: "Scoring ICE Automatique",
    titleEn: "Automatic ICE Scoring",
    descFr: "Chaque recommandation est priorisée par Impact, Confiance et Facilité d'exécution.",
    descEn: "Every recommendation is prioritized by Impact, Confidence and Ease of execution.",
    color: "#f59e0b",
  },
  {
    icon: Search,
    titleFr: "Audit Instantané",
    titleEn: "Instant Audit",
    descFr: "Collez votre URL et obtenez un audit SEO technique complet en 30 secondes, sans créer de compte.",
    descEn: "Paste your URL and get a complete technical SEO audit in 30 seconds, no account needed.",
    color: "#ef4444",
  },
  {
    icon: Globe,
    titleFr: "Intégrations Natives",
    titleEn: "Native Integrations",
    descFr: "Google Analytics, Search Console, Google Ads, Meta Business, CMS et plus encore en 1 clic.",
    descEn: "Google Analytics, Search Console, Google Ads, Meta Business, CMS and more in 1 click.",
    color: "#06b6d4",
  },
  {
    icon: FileText,
    titleFr: "Rapports Automatisés",
    titleEn: "Automated Reports",
    descFr: "Briefings quotidiens, rapports hebdomadaires et tableaux de bord générés automatiquement par vos agents.",
    descEn: "Daily briefings, weekly reports and dashboards automatically generated by your agents.",
    color: "#ec4899",
  },
  {
    icon: Lock,
    titleFr: "Sécurité Enterprise",
    titleEn: "Enterprise Security",
    descFr: "RGPD, chiffrement AES-256, audit trail complet, RBAC et hébergement européen.",
    descEn: "GDPR, AES-256 encryption, complete audit trail, RBAC and European hosting.",
    color: "#dc2626",
  },
  {
    icon: Bell,
    titleFr: "Alertes Intelligentes",
    titleEn: "Smart Alerts",
    descFr: "Notifications en temps réel sur les anomalies, opportunités et actions requises.",
    descEn: "Real-time notifications on anomalies, opportunities and required actions.",
    color: "#f97316",
  },
  {
    icon: Workflow,
    titleFr: "Automatisations",
    titleEn: "Automations",
    descFr: "Workflows personnalisés pour automatiser vos processus métier récurrents.",
    descEn: "Custom workflows to automate your recurring business processes.",
    color: "#a855f7",
  },
  {
    icon: Clock,
    titleFr: "Disponibilité 24/7",
    titleEn: "24/7 Availability",
    descFr: "Vos agents ne dorment jamais. Monitoring continu, exécution permanente.",
    descEn: "Your agents never sleep. Continuous monitoring, permanent execution.",
    color: "#22c55e",
  },
  {
    icon: TrendingUp,
    titleFr: "ROI Mesurable",
    titleEn: "Measurable ROI",
    descFr: "Dashboard ROI intégré pour mesurer l'impact réel de chaque agent sur votre croissance.",
    descEn: "Built-in ROI dashboard to measure each agent's real impact on your growth.",
    color: "#2563eb",
  },
];

export default function Features() {
  const { i18n } = useTranslation();
  const lang = i18n.language.startsWith("fr") ? "fr" : "en";

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: lang === "fr" ? "Fonctionnalités - Growth OS" : "Features - Growth OS",
    description: lang === "fr"
      ? "Découvrez toutes les fonctionnalités de Growth OS : 39 agents IA, 11 départements, scoring ICE et plus."
      : "Discover all Growth OS features: 39 AI agents, 11 departments, ICE scoring and more.",
  };

  return (
    <>
      <SEOHead
        title={lang === "fr" ? "Fonctionnalités" : "Features"}
        description={
          lang === "fr"
            ? "Découvrez toutes les fonctionnalités de Growth OS pour automatiser votre croissance."
            : "Discover all Growth OS features to automate your growth."
        }
        canonical="/features"
        structuredData={structuredData}
      />

      <div className="min-h-screen bg-background">
        {/* Hero */}
        <section className="py-20 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-b from-primary/5 to-transparent" />
          <div className="container mx-auto px-4 relative text-center">
            <Badge variant="agent" className="mb-4">
              {lang === "fr" ? "Fonctionnalités" : "Features"}
            </Badge>
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              {lang === "fr" ? "Tout ce dont vous avez " : "Everything you "}
              <span className="gradient-text">
                {lang === "fr" ? "besoin" : "need"}
              </span>
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              {lang === "fr"
                ? "39 agents IA, 11 départements, intégrations natives et sécurité enterprise. Growth OS automatise votre croissance de A à Z."
                : "39 AI agents, 11 departments, native integrations and enterprise security. Growth OS automates your growth from A to Z."}
            </p>
          </div>
        </section>

        {/* Core Features Grid */}
        <section className="py-16">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {CORE_FEATURES.map((feature, index) => {
                const Icon = feature.icon;
                return (
                  <Card
                    key={index}
                    className="overflow-hidden hover:border-primary/30 transition-all duration-300 animate-fade-in-up"
                    style={{ animationDelay: `${index * 50}ms` }}
                  >
                    <CardContent className="p-6">
                      <div
                        className="w-12 h-12 rounded-xl flex items-center justify-center mb-4"
                        style={{ backgroundColor: `${feature.color}15` }}
                      >
                        <Icon className="w-6 h-6" style={{ color: feature.color }} />
                      </div>
                      <h3 className="font-bold text-lg mb-2">
                        {lang === "fr" ? feature.titleFr : feature.titleEn}
                      </h3>
                      <p className="text-sm text-muted-foreground">
                        {lang === "fr" ? feature.descFr : feature.descEn}
                      </p>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>
        </section>

        {/* Departments Overview */}
        <section className="py-16 bg-secondary/30">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold mb-4">
                {lang === "fr" ? "11 Départements spécialisés" : "11 Specialized departments"}
              </h2>
              <p className="text-muted-foreground max-w-xl mx-auto">
                {lang === "fr"
                  ? "Chaque département est autonome avec ses agents IA dédiés."
                  : "Each department is autonomous with its dedicated AI agents."}
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {DEPARTMENTS_CATALOG.filter(d => d.slug !== "direction").map((dept) => {
                const DeptIcon = dept.icon;
                return (
                  <Link key={dept.slug} to={`/departments/${dept.slug}`}>
                    <Card className="hover:border-primary/30 transition-all group">
                      <CardContent className="p-5">
                        <div className="flex items-start gap-4">
                          <div
                            className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0"
                            style={{ backgroundColor: `${dept.color}20` }}
                          >
                            <DeptIcon className="w-5 h-5" style={{ color: dept.color }} />
                          </div>
                          <div className="flex-1">
                            <div className="flex items-center justify-between">
                              <h3 className="font-bold text-sm group-hover:text-primary transition-colors">
                                {dept.name[lang]}
                              </h3>
                              <Badge variant="outline" className="text-xs">
                                {dept.agentCount} agents
                              </Badge>
                            </div>
                            <p className="text-xs text-muted-foreground mt-1">
                              {dept.description[lang].slice(0, 100)}...
                            </p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </Link>
                );
              })}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-16">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              {lang === "fr"
                ? "Prêt à automatiser votre croissance ?"
                : "Ready to automate your growth?"}
            </h2>
            <p className="text-muted-foreground mb-8 max-w-xl mx-auto">
              {lang === "fr"
                ? "Essai gratuit de 14 jours. Aucune carte bancaire requise."
                : "14-day free trial. No credit card required."}
            </p>
            <div className="flex gap-4 justify-center flex-wrap">
              <Link to="/auth?tab=signup">
                <Button variant="hero" size="lg">
                  {lang === "fr" ? "Essai gratuit" : "Free trial"}
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Button>
              </Link>
              <Link to="/agents">
                <Button variant="outline" size="lg">
                  {lang === "fr" ? "Voir les 39 agents" : "See all 39 agents"}
                </Button>
              </Link>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
